name: I3C CI
on:
  push:
    branches: ["main", "87005-public_ci"]
  pull_request:
  workflow_dispatch:

jobs:
  axi_verification:
    name: Axi Verification
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: "noninteractive"
      VERIBLE_VERSION: "v0.0-4023-gc1271a00/verible-v0.0-4023-gc1271a00-linux-static-x86_64"
    steps:
      - name: Install dependencies
        run: |
          sudo apt -qqy update
          sudo apt -qqy --no-install-recommends install help2man libfl-dev make g++ git bison flex gperf \
                                                        libreadline-dev libbz2-dev autoconf python3-sphinx \
                                                        python3-docopt

      - name: Setup repository
        uses: actions/checkout@v4

      - name: Get Submodules
        run: |
          git submodule update --init --recursive

      - name: Install Pyenv
        run: |
          ./install.sh

      - name: Install verible
        run: |
          wget -qO- https://github.com/chipsalliance/verible/releases/download/$VERIBLE_VERSION.tar.gz | \
          gunzip | tar xf - --strip-components 2 --directory /usr/local/bin 

      - name: Build Verilator
        run: |
          git clone https://github.com/verilator/verilator -b v5.024
          cd verilator
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install
          verilator --version

      - name: Verify
        env:
          MAKE_TARGET: "tests-axi"
        run: |
          ./install.sh
          make install-uvm
          source activate.sh
          make ${MAKE_TARGET}
      - name: Process coverage
        run: |
         python3.11 -m venv .venv
         source .venv/bin/activate
         python3.11 -m pip install -r requirements.txt
         python3.11 -m pip install git+https://github.com/antmicro/info-process.git
         mkdir -p artifacts/results
         source .venv/bin/activate

         COVERAGE_DIR="$(TMP="${CI_JOB_NAME////_}"; echo "artifacts/coverage/${TMP// /_}")"
         mkdir -p "${COVERAGE_DIR}"
         COVERAGE_DIR="$(realpath "${COVERAGE_DIR}")"
         (cd verification/cocotb && find -name \*.dat -not -name Vtop\*.dat | xargs cp -Lrv --parents -t "${COVERAGE_DIR}")

         for cov in $(find "${COVERAGE_DIR}" -type f -name \*.dat); do
          out_file="$(dirname "${cov}")/$(basename "${cov}" .dat)_verilator.info"
          verilator_coverage --skip-toggle --write-info "${out_file}" "${cov}"
          verilator_coverage --toggle-only --write-info "${out_file%%_all_verilator.info}_toggle_verilator.info" "${cov}"
          rm "${cov}"

          info-process extract --coverage-type line --output "${out_file%%_all_verilator.info}_line_verilator.info" "${out_file}"
          info-process extract --coverage-type cond --output "${out_file%%_all_verilator.info}_cond_verilator.info" "${out_file}"
          info-process extract --coverage-type branch --output "${out_file%%_all_verilator.info}_branch_verilator.info" "${out_file}"
          rm "${out_file}"
         done
         tar -c `find verification/cocotb -name \*.xml -o -name \*.log -o -name \*.info -o -name \*.vcd -o -name \*.dat -not -name Vtop*.dat` -f logs.tar
         cd artifacts/results
         tar xf ../../logs.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: axi-verification
          path: artifacts

  coverage:
    name: Process Coverage
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    needs: [ custom_axi_verification ]
    container: antmicro/centos-dev-tools
    env:
      GHA_EXTERNAL_DISK: additional-tools-all
      GHA_SA: gh-sa-i3c-core-uploader
    steps:
      - name: Get repository
        run: _secret_custom_checkout:6
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_SUBMODULES: RECURSIVE
      - name: Prepare platform
        run: _secret_i3c_platform_prepare:3
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Process Coverage
        run: _secret_i3c_process_coverage:1
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  custom_lint:
    name: Custom Lint
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    container: antmicro/centos-dev-tools
    env:
      GHA_EXTERNAL_DISK: additional-tools-all
      GHA_SA: gh-sa-i3c-core-uploader
    steps:
      - name: Get repository
        run: _secret_custom_checkout:6
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_SUBMODULES: RECURSIVE
      - name: Custom Lint
        run: _secret_i3c_custom_lint:13
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  custom_axi_verification:
    name: Custom Axi Verification
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    container: antmicro/centos-dev-tools
    env:
      GHA_EXTERNAL_DISK: additional-tools-all
      GHA_SA: gh-sa-i3c-core-uploader
    steps:
      - name: Get repository
        run: _secret_custom_checkout:6
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_SUBMODULES: RECURSIVE
      - name: Prepare platform
        run: _secret_i3c_platform_prepare:3
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Custom Axi Verification
        run: _secret_i3c_custom_axi_test:14
        env:
          SIM_RETRY_CONDITION: "Check your license file|Cannot connect to the license server|Failed to obtain license|License check .* failed"
          TEST_COVERAGE_ENABLE: 1
          CI_PARALLEL_INDEX: 1
          CI_PARALLEL_TOTAL: 1
          TEST_ITERATIONS: 1
          MAKE_TARGET: "tests-axi"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
