name: I3C CI
on:
  push:
    branches: ["main", "87005-public_ci", "gpla/ci-tests"]
  pull_request:
  workflow_dispatch:

jobs:
  verification_axi:
    name: Verification AXI
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    container: centos:8
    steps:
      - name: test
        run: _secret_custom_upload_artifact:6
        env:
          INPUT_NAME: test
          INPUT_PATH: /etc/resolv.conf
